In [31]:
a_25 = np.array([11,12,13,14,15])
print(a_25)

[11 12 13 14 15]


In [33]:
b_25 = np.array([[16,17,18,19,20],[21,22,23,24,25]])
print(b_25)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [34]:
c_25 = np.array([[[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,24]]])
print(c_25)

[[[11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 24]]]


In [36]:
a_25.ndim

1

In [37]:
b_25.ndim

2

In [38]:
c_25.ndim

3

In [27]:
import numpy as np

In [55]:
d_25 = np.array ([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(d_25)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
d_25[0,3]

14

In [57]:
d_25[1,:]

array([16, 17, 18, 19, 20])

In [58]:
d_25[:,2]

array([13, 18, 23])

In [59]:
d_25[0,1:3]

array([12, 13])

In [60]:
d_25[0,0:3:2]

array([11, 13])

In [61]:
d_25[0,0]  = 100
print(d_25)

[[100  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]
